version: "3"

services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2
